# Generated by Django 2.0.3 on 2018-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('ruc', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('rubro', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
