# Generated by Django 2.0.3 on 2018-03-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0002_remove_especialidad_carrera'),
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='especialidad_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidad.Especialidad'),
        ),
    ]
